In [8]:
import torch as torch
import torch.nn as nn

In [67]:
B = 2
WH = 5
F = 8


input = torch.ones(B, WH, F)

for b in range(B):
    for wh in range(WH):
        input[b, wh, :] = torch.arange(0, F)

In [68]:
input[1, 1, :]

tensor([0., 1., 2., 3., 4., 5., 6., 7.])

In [77]:
nums = torch.arange(0, F, dtype=float)
mean = nums.sum() / len(nums)
var = torch.var(nums, False)

In [78]:
norm = (nums - mean) / torch.sqrt(var)
norm

tensor([-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,  1.5275],
       dtype=torch.float64)

In [81]:
m = nn.LayerNorm(F, eps=0.0)
m.eval()
m(input)

tensor([[[-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,
           1.5275],
         [-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,
           1.5275],
         [-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,
           1.5275],
         [-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,
           1.5275],
         [-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,
           1.5275]],

        [[-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,
           1.5275],
         [-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,
           1.5275],
         [-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,
           1.5275],
         [-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,
           1.5275],
         [-1.5275, -1.0911, -0.6547, -0.2182,  0.2182,  0.6547,  1.0911,
           1.5275]]], grad_fn=<NativeLayerNormBackward>)

In [82]:
m = nn.LayerNorm(F)

In [83]:
m

LayerNorm((8,), eps=1e-05, elementwise_affine=True)

In [84]:
[p for p in m.named_parameters()]

[('weight',
  Parameter containing:
  tensor([1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True))]

In [85]:
m.weight = torch.nn.Parameter(torch.tensor([1.0, 2, 3, 4, 5, 5, 7, 8]))

In [86]:
m.bias = torch.nn.Parameter(torch.tensor([0.1, .2, .3, .4, .5, .5, .7, .8]))

In [87]:
m(input)

tensor([[[-1.4275, -1.9822, -1.6640, -0.4729,  1.5911,  3.7733,  8.3376,
          13.0202],
         [-1.4275, -1.9822, -1.6640, -0.4729,  1.5911,  3.7733,  8.3376,
          13.0202],
         [-1.4275, -1.9822, -1.6640, -0.4729,  1.5911,  3.7733,  8.3376,
          13.0202],
         [-1.4275, -1.9822, -1.6640, -0.4729,  1.5911,  3.7733,  8.3376,
          13.0202],
         [-1.4275, -1.9822, -1.6640, -0.4729,  1.5911,  3.7733,  8.3376,
          13.0202]],

        [[-1.4275, -1.9822, -1.6640, -0.4729,  1.5911,  3.7733,  8.3376,
          13.0202],
         [-1.4275, -1.9822, -1.6640, -0.4729,  1.5911,  3.7733,  8.3376,
          13.0202],
         [-1.4275, -1.9822, -1.6640, -0.4729,  1.5911,  3.7733,  8.3376,
          13.0202],
         [-1.4275, -1.9822, -1.6640, -0.4729,  1.5911,  3.7733,  8.3376,
          13.0202],
         [-1.4275, -1.9822, -1.6640, -0.4729,  1.5911,  3.7733,  8.3376,
          13.0202]]], grad_fn=<NativeLayerNormBackward>)